#ifndef WEIGHTEDBUDDYMEMORYALLOCATOR_ONEBINTESTER_H
#define WEIGHTEDBUDDYMEMORYALLOCATOR_ONEBINTESTER_H

#include "oneBin.h"
#include "helpers.h"

#endif //WEIGHTEDBUDDYMEMORYALLOCATOR_ONEBINTESTER_H
