#ifndef WEIGHTEDBUDDYMEMORYALLOCATOR_SPHEAP_H
#define WEIGHTEDBUDDYMEMORYALLOCATOR_SPHEAP_H


#define SIZEOFHEAP 8 //(in 2^n MB)
#define MIN_ALLOCATABLE_BYTES 4 //(SIZEOF(INT) = 4


#endif //WEIGHTEDBUDDYMEMORYALLOCATOR_SPHEAP_H
